### ISSUE TITLE
[NEO X] Setting gaslimit is ignored.

### ISSUE THREAD

**Issue by snakeyrob** [NeoNEXT/neoline#145]
I'm trying to set a higher gaslimit on a transaction since estimateGas can return a low value that causes the transaction to run out of gas.
For metamask it works to force a gas limit but neoline seems to ignore the properties.

For example this code.
`
// Join the pool
      const joinTx = await lotteryContract.finalizePool(poolId,{
        gasLimit: ethers.toBigInt('200000') // Enforce your gas limit here
      });

      await joinTx.wait();
`

Will give me this result

![Image](https://github.com/user-attachments/assets/378cb11a-fda9-494a-a53a-d0946fa248f1)

it shows that the website is suggesting to use another value, but unless the user actively does this it's ignored.
and you only see this in the advanced menu which is very counter intuitive, shouldn't this be the other way around?

**Comment by haiwulei** [comment]
We will adjust the default logic to prioritize the developer’s custom gasLimit instead of overriding it with the default estimated value.

**Comment by haiwulei** [comment]
Fixed in v5.2.1

**Comment by snakeyrob** [comment]
I just tried but the same issue persists

![Image](https://github.com/user-attachments/assets/d94efc8c-209a-452a-b731-d5f010f9c53a)

**Comment by haiwulei** [comment]
Did you only set gas? You should set both gas and maxFeePerGas.

**Comment by snakeyrob** [comment]
I provided an example of my code where you can see gasLimit: ethers.toBigInt('200000') which is accepted fine by other wallets but not neoline. still seems like a bug to me. But for my use case I can go with maxFeePerGas as that does seem to work the same across wallets. Thanks.

**Comment by haiwulei** [comment]
The example you provided is wrapped, so I can’t see the exact parameters you’re passing. Could you share a more specific example? like the one shown in the image below.

![Image](https://github.com/user-attachments/assets/1fa77e09-42d8-4f68-835d-b13050be8afb)
